_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
                - 98
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.1
            "6": 4.41.2
            "8":
                - 5
                - 9
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 5
dataset:
    value: DGM4
epochs:
    value: 11
eval_steps:
    value: 2000
learning_rate:
    value: 1e-06
use_lora:
    value: false
world_size:
    value: 4
